version: "3"
services:
  db:
    image: pyrodb:1.0
    platform: linux/x86_64
    container_name: pyrodb-1.0
    build:
      context: .
      dockerfile: ./Dockerfile.pyrodb
    ports:
      - "12345:3306"
    restart: always

  adminer:
    image: adminer
    platform: linux/x86_64
    container_name: adminer9984
    ports:
      - 9984:8080

  redis:
    image: redis
    platform: linux/x86_64
    container_name: redis15552
    hostname: redis15552
    command: redis-server --requirepass redis1234 --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 15552:6379
